version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./.env:/usr/src/.env
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
